### ISSUE TITLE
How to make Like not only from User id, but can from any id too? 

### ISSUE THREAD

**Issue by diarsa** [risul3/laravel-like-comment#11]
When I click like or comment, I get this error in console. 
`projectname/laravellikecomment/like/vote?item_id=20&vote=-1 Failed to load resource: the server responded with a status of 404 (Not Found)`

My project is run in `projectname/public` when I change the error link and add `public` or like this `projectname/public/laravellikecomment/like/vote?item_id=20&vote=-1`, it's work, 
How to handle this?

**Comment by diarsa** [comment]
I want the like button can use from 
`if user login` 
or 
`if user login and have other id table`

============

`if user only login`, the `id` is `email user`
or 
`if user login and have other id table`, the `id` is `other id table`

I try to change `$userId = Auth::user()->id;` to `$userId = $ids;` and the `$ids` is from 

`if (!empty($idwi)) {
      		$ids = $idwi->id;
      	} else {
      		$ids = Auth::user()->email;
      	}`

it's work when the user `only login`, but I get the error when `if user login and have other id table` the error is `[object Object]` and in console is `Uncaught SyntaxError: Unexpected token }
http://localhost/public/laravellikecomment/like/vote?item_id=34&vote=1 Failed to load resource: the server responded with a status of 404 (Not Found)`

How to I handle this? Help me please.

**Comment by risul3** [comment]
Sorry, your problem is not clear to me. Users must be logged in to like or comment. It is necessary to keep track of like and comment.
