### ISSUE TITLE
laravel5.4 install failure

### ISSUE THREAD

**Issue by glore** [risul3/laravel-like-comment#13]
[2017-02-15 18:27:15] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::share() in /srv/ufutx/ufutx.center/vendor/risul/laravel-like- comment/src/LikeCommentServiceProvider.php:34
 Stack trace:
 #0 /srv/ufutx/ufutx.center/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(568): risul\LaravelLikeComment\LikeCommentServiceProvider->register()
 #1 /srv/ufutx/ufutx.center/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(risul\LaravelLikeComment\LikeCommentServiceProvider))
 #2 /srv/ufutx/ufutx.center/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(543): Illuminate\Foundation\ProviderRepository->load(Array)
 #3 /srv/ufutx/ufutx.center/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
 #4 /srv/ufutx/ufutx.center/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
 #5 /srv/ufutx/ufutx.center/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(270): Illuminate\Foundation\Application->bootstrapWith(Array)
 #6 /srv/ufutx/ufutx.center/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(115): Illuminate\Foundation\Console\Kernel->bootstrap()
 #7 /srv/ufutx/ufutx.center/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
 #8 {main}

**Comment by ziymed** [comment]
Laravel no longer use share()

go to vendor and search the src and open the file LikeCommentServiceProvider.php  and change this ; 
`$this->app['LaravelLikeComment'] = $this->app->share(function($app) {
       return new LaravelLikeComment;
});`

by this : 
`$this->app->singleton('LaravelLikeComment', function ($app) {
        return new LaravelLikeComment;
});`

**Comment by risul3** [comment]
Fixed
