### ISSUE TITLE
problem with comment

### ISSUE THREAD

**Issue by havanan** [risul3/laravel-like-comment#17]
i have a problem with comment, can u help me ? 
https://drive.google.com/file/d/0B66s0zNQmmFLT1FlaTdMOG52TjA/view?usp=sharing

**Comment by risul3** [comment]
Sorry I don't understand the language. Can you please tell me the error in
English please.
Thanks

**Comment by havanan** [comment]
Can you help me through teamview?


2017-10-26 10:14 GMT+07:00 Risul Islam <notifications@github.com>:

> Sorry I don't understand the language. Can you please tell me the error in
> English please.
> Thanks
>
