### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by lettertoamit** [risul3/laravel-like-comment#3]
I am getting this error ...... . Not able to rectify it

**Comment by risul3** [comment]
As far I am concerned I did not used array_merge() any where in this package. Are you sure you are facing this issue in this package?

**Comment by lettertoamit** [comment]
Yes I am positive

**Comment by lettertoamit** [comment]
yes i faced issue ........ but i migrated to other plugin
