### ISSUE TITLE
Trigger Events on Comment Submit

### ISSUE THREAD

**Issue by maximusblade** [risul3/laravel-like-comment#4]
Hi there
What would be the best way to implement an event trigger on comment submit or like event?

I would like to send an email or notification to all participating users of the thread?

any help would be great here. thank you

**Comment by risul3** [comment]
```
$('.laravelLike-icon').on('click', function(){
  var item_id = $(this).data('item-id');
  var vote = $(this).data('vote');  // 1 is Like and -1 is dislike
})

```

```
$(document).on('submit', '.laravelComment-form', function(){
    var item_id = $(this).data('item');
    var comment = $('textarea#'+parent+'-textarea').val();
})
```

I am handling like and comment using these method.
