### ISSUE TITLE
how to write A comment On a specific POST ?

### ISSUE THREAD

**Issue by mohammedabdallah** [risul3/laravel-like-comment#8]
if i have multiple posts there's any way to distinct between their comments ?

**Comment by risul3** [comment]
You need to send a `comment_item_id` for each post. For example-
FIrst post with id post_1
`@include('laravelLikeComment::comment', ['comment_item_id' => 'post_1'])`
Second post with id post_2
`@include('laravelLikeComment::comment', ['comment_item_id' => 'post_2'])`

**Comment by mohammedabdallah** [comment]
Many thanks @risul3 Now it's work right
